### ISSUE TITLE
Request for a region parameter

### ISSUE THREAD

**Issue by mrsean2k** [lucas-subli/angular-freshdesk#1]
The current widget constructs a URL using the default prefix of
`https://widget.freshworks.com/widgets/`

This will fail with  a 403 for widgets intended for use in other locations, such as the eu where
`https://euc-widget.freshworks.com/widgets/`
is the correct URL

Is it possible to add a property to the config object to supply the whole prefix or an optional regional portion of the url?

**Comment by lucas-subli** [comment]
Hey, I am just maintaining this fork of the original lib for legacy reasons.

I don't intended to change any functionality beyond simply keeping it up to date with the latest angular version.

That being said the code is very small (3 files), I would recommend just copying the code to your project and making the necessary updates.
